SELECT * FROM CUSTOMER;
-- Total Revenue generated by male and female customers -- 
select gender, sum(purchase_amount) as Revenue
from customer 
group by gender;
### Revenue generated by male is higher than female ###

-- Customer who used the discount but still spent more than average amount --
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount > (select AVG(purchase_amount) from customer);

-- Top 5 Products with higest average review rating --

select item_purchased ,AVG(review_rating) as avg_rating
from customer
 group by item_purchased
 order by avg_rating desc
 limit 5;
 
 -- Comparision of the average purchase_amount between Standard and express shipping -- 
 
select ROUND(AVG(purchase_amount),2) , shipping_type
from customer
where shipping_type = 'Standard' or shipping_type ='Express'

group by shipping_type;


-- DO subsribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.--
select subscription_status, 
count(customer_id) as total_customer, AVG(purchase_amount) as avg_amount , SUM(purchase_amount) as Total_Revenue
from customer
group by subscription_status;
 
 -- Which 5 products have the highest percentage of purchases with discounts applied --
 select item_purchased,
 ROUND (100 * sum(case when discount_applied = 'Yes' Then 1 ELSE 0 END)/COUNT(*), 2 ) as discount_rate
 from customer
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 -- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases = '1' THEN 'New'
WHEN previous_purchases BETWEEN '2' AND '10' THEN 'Returning'
ELSE 'loyal'
end as customer_segment
from customer)

SELECT customer_segment, count(*) as Number_of_customer
from customer_type
group by customer_segment;


-- What are the top 3 most purchased products within each category? 
select category, item_purchased
from customer 
group by item_purchased;
