select * from customer;

-- Revenue Generated by male vs female customer --
select gender,sum(purchase_amount) as Total_Revenue 
from customer
group by gender;

-- customers who used a discount but still spent more than the average purchase amount -- 
select customer_id, purchase_amount 
from customer
where discount_applied ='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Top 5 products with the highest average review rating-- 
select item_purchased , Round(avg(review_rating),2) as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating desc
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.  -- 
select avg(purchase_amount) as avg_purchase_amount, shipping_type
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. --
select 
count(customer_id) as total_customers,
avg(purchase_amount) as avg_purchase_amount ,
 sum(purchase_amount) as total_revenue,
 subscription_status
from customer
group by subscription_status;

-- Which 5 products have the highest percentage of purchases with discounts applied? --
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. --
with customer_type as (
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 2 Then 'New'
when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal' 
end as customer_segment
from customer)
select customer_segment, count(*) as Total_number_of_customer
from customer_type
group by customer_segment;

-- What are the top 3 most purchased products within each category? --
with item_counts as(
select item_purchased, category, count(customer_id) as total_orders,
row_number() over( partition by category order by  count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)
select item_rank,item_purchased, total_orders
from item_counts
where 
item_rank<=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? -- 


select count(customer_id) as repeat_buyers,  subscription_status
from customer
where previous_purchases >5  
group by subscription_status;


-- What is the revenue contribution of each age group? -- 
select sum(purchase_amount) as Total_Reevenue, age_group
from customer
group by age_group;

